name: Docker CI & CD Prod

on:
  workflow_dispatch:
    inputs:
      commit-sha:
        description: 'hash of package we want to deploy'
        required: true

      
env:
  REPO_NAME: devop-with-github/nodejs-containerized-webapp
  IMAGE_REGISTRY_URL: docker.pkg.github.com
  AZURE_WEBAPP_NAME: tic-tac-toe
  DEPLOY_END: prod

jobs:
  Deploy:
    if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest
    name: Deploy app container to Prod Azure
    steps:
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/docker-login@v1
        with:
          login-server: ${{env.IMAGE_REGISTRY_URL}}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy web app container
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.DEPLOY_END}}-${{env.AZURE_WEBAPP_NAME}}
          images: ${{env.IMAGE_REGISTRY_URL}}/${{ env.REPO_NAME}}/${{env.DEPLOY_END}}-${{ env.AZURE_WEBAPP_NAME }}:${{ github.sha }}

      - name: Azure logout
        run: |
          az logout
