name: Azure Bicep IaaC

on: 
  push:
    branches:
      - main
    paths:
      - 'infra/**'
      
env:
  AZURE_RESOURCE_GROUP: cd-with-actions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: dev-${{env.AZURE_RESOURCE_GROUP}}
        template: ./azuredeploy.bicep
        parameters: storagePrefix=mystore
