
name: Azure Bicep IaaC

on: 
  push:
    branches:
      - main
      - IaaC
    paths:
      - 'infra/**'
      
env:
  AZURE_RESOURCE_GROUP: cd-with-actions-test
  AZURE_LOCATION: '"Central US"'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: create resource groups if it deoes not exist
      run: |
        az group create --location ${{env.AZURE_LOCATION}} --name dev-${{env.AZURE_RESOURCE_GROUP}} --subscription ${{secrets.AZURE_SUBSCRIPTION_ID}}
        az group create --location ${{env.AZURE_LOCATION}} --name prod-${{env.AZURE_RESOURCE_GROUP}} --subscription ${{secrets.AZURE_SUBSCRIPTION_ID}}
        
      # Deploy Bicep file
    - name: deploy dev
      if: success()
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: dev-${{env.AZURE_RESOURCE_GROUP}}
        template: ./infra/azuredeploy.bicep
        parameters: envprefix=dev anotherparam=test

