
name: Azure Bicep IaaC

on: 
  push:
    branches:
      - main
      - IaaC
    paths:
      - 'infra/**'
      
env:
  AZURE_RESOURCE_GROUP: cd-with-actions-test
  AZURE_LOCATION: '"Central US"'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: if_group_exists
      run: |
        devRgExisted=$(az group exists --name dev-${{env.AZURE_RESOURCE_GROUP}} --subscription ${{secrets.AZURE_SUBSCRIPTION_ID}})
        prodRgExisted=$(az group exists --name prod-${{env.AZURE_RESOURCE_GROUP}} --subscription ${{secrets.AZURE_SUBSCRIPTION_ID}})
        echo "::set-output name=isDevGroupExisted::$devRgExisted\n"
        echo "::set-output name=isProdGroupExisted::$prodRgExisted\n"
        echo "dev group $devRgExisted"
        echo "prod group $prodRgExisted"
      
    - name: create dev group if it deoes not exist
      if: ${{steps.if_group_exists.output.isDevGroupExisted == 'false' }}
      run: |
        az group create --location ${{env.AZURE_LOCATION}} --name dev-${{env.AZURE_RESOURCE_GROUP}} --subscription ${{secrets.AZURE_SUBSCRIPTION_ID}}

    - name: create prod group if it deoes not exist
      if: ${{steps.if_group_exists.output.isProdGroupExisted == 'false' }}
      run: |
        az group create --location ${{env.AZURE_LOCATION}} --name prod-${{env.AZURE_RESOURCE_GROUP}} --subscription ${{secrets.AZURE_SUBSCRIPTION_ID}}
        
      # Deploy Bicep file
    - name: deploy dev
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: dev-${{env.AZURE_RESOURCE_GROUP}}
        template: ../../infra/azuredeploy.bicep
        parameters: envprefix=dev anotherparam=test

    - name: deploy prod
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: prod-${{env.AZURE_RESOURCE_GROUP}}
        template: ../../infra/azuredeploy.bicep
        parameters: envprefix=prod anotherparam=test
